---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devspaces
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default
  source:
    repoURL: https://github.com/lennysh/aap-openshift-argocd-gitops-demo.git
    path: app-devspaces
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-devspaces
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
  ignoreDifferences:
    - group: org.eclipse.che
      kind: CheCluster
      name: devspaces
      jsonPointers:
        - /spec
  retry:
    limit: 5
    backoff:
      duration: 5s
      factor: 2
      maxDuration: 10m
