---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-checluster-manager
  namespace: openshift-operators
  annotations:
    argocd.argoproj.io/sync-wave: "1"
rules:
- apiGroups:
  - org.eclipse.che
  resources:
  - checlusters
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
...
