---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-checluster-manager
  namespace: openshift-operators
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/name: devspaces
    app.kubernetes.io/part-of: devspaces-argocd
    app.kubernetes.io/managed-by: argocd
rules:
- apiGroups:
  - org.eclipse.che
  resources:
  - checlusters
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - operators.coreos.com
  resources:
  - subscriptions
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
  - deletecollection
...
